apiVersion: v1
kind: Service
metadata:
  name: fcg-payments-api-service
spec:
  selector:
    app: fcg-payments-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
