apiVersion: apps/v1
kind: Deployment
metadata:
  name: fcg-payments-api
  labels:
    app: fcg-payments-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fcg-payments-api
  template:
    metadata:
      labels:
        app: fcg-payments-api
    spec:
      serviceAccountName: fcg-payments-sa
      containers:
        - name: fcg-payments-api
          image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/fcg-payments-api:${IMAGE_TAG}
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"
          envFrom:
            - configMapRef:
                name: fcg-payments-config
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
