apiVersion: apps/v1
kind: Deployment
metadata:
  name: fcg-payments-worker
  labels:
    app: fcg-payments-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fcg-payments-worker
  template:
    metadata:
      labels:
        app: fcg-payments-worker
    spec:
      containers:
        - name: fcg-payments-worker
          image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/fcg-payments-worker:${IMAGE_TAG}
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"
            - name: Kafka__BootstrapServers
              value: "kafka:9092"
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "300m"
              memory: "256Mi"
